Update pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,18 +1,49 @@
 #!/usr/bin/env bash
 
-echo -e "Running clang-format-diff...\n"
+function run_clang_format_diff() {
+    echo "Running clang-format-diff..."
+    command -v "clang-format-diff.py" > /dev/null 2>&1 ||
+    if [ "$?" ]; then
+        echo "clang-format-diff.py not found, skip!"
+        echo "Please setup clang-format-diff.py"
+        exit 0
+    fi
 
-fmt_diff=$(git diff --no-ext -U0 --no-color --relative --cached | clang-format-diff.py -p1)
+    fmt_diff=$(git diff --no-ext -U0 --no-color --relative --cached | clang-format-diff.py -p1)
 
-colorize_diff='
-    /^+/ { printf "\033[1;32m" }
-    /^-/ { printf "\033[1;31m" }
-    // { print $0 "\033[0m"; }'
+    colorize_diff='
+        /^+/ { printf "\033[1;32m" }
+        /^-/ { printf "\033[1;31m" }
+        // { print $0 "\033[0m"; }'
 
-if [ -n "$fmt_diff" ]; then
-    echo "$fmt_diff" | awk "$colorize_diff"
-    echo -e "\nPlease re-format above files before commit"
-    exit 1
-fi
+    if [ -n "${fmt_diff}" ]; then
+        echo "${fmt_diff}" | awk "${colorize_diff}"
+        echo -e "\nPlease re-format above files before commit"
+        exit 1
+    fi
 
-echo "clang-format-diff passed"
+    echo "clang-format-diff passed"
+}
+
+function run_line_length_check() {
+    echo "Running line-length check..."
+    command -v "cpplint" > /dev/null 2>&1 ||
+    if [ "$?" ]; then
+        echo "cpplint not found, skip!"
+        echo "please install cpplint"
+        exit 0
+    fi
+
+    changed_files=$(git diff --cached --name-only | grep -iE '\.(cpp|h)$')
+    if [ -n "${changed_files}" ]; then
+        cpplint --quiet --filter=-,+whitespace/line_length --linelength=100 ${changed_files} ||
+        if [ "$?" ]; then
+            exit 1
+        fi
+    fi
+
+    echo "Line-length check passed"
+}
+
+run_clang_format_diff && \
+run_line_length_check
